---
title: "Homework 2"
author: "State Your Name"
format:
  html:
    self-contained: true
---

## The Data

There is 1000 observations, spread across 10 csv files in a zip. 

1.    First you will need to use `unzip` to unzip it. 

2.    Next, you will need to generate a vector of all of those files with `list.files`. It works like this:

```{r}
#| eval: false

file_list <- list.files("~/data_wrangling_class/homework/data/", pattern = ".csv", 
                        all.files = TRUE, full.names = TRUE)
```

3. You can use a `for loop`, an `lapply`, or a `purrr::map` statement to bring all of those files together into one data frame. The columns are in the same order, so feel free to bind them together. If you end up with a list of data frames, you can use `do.call(rbind, your_object)`, `dplyr::bind_rows`, or `data.table::rbindlist` to bring them together.

## Data Prep Tasks

This part should live in a separate qmd file.

1.    Create a function to clean ratings & length variables.

2.    Create a total length (as in movie length) column.

3.    Create a date delta between release time and review time.

4.    Pick a word from the reviews and count how many times that word appears.

5.    Create an aggregated data set for the unique movies. There should be movies, average ratings, release year, genre, and total number of reviews.

6.    You should have two data frames, so `save` those objects for the next step.

## Analytic Tasks

The tasks below should live in a separate qmd from your prep work. You will want to `load` your data from the previous step.

1.    Which genre has the highest critic rating? Viewer rating?

2.    What is the relationship between movie length and average rating?

3.    What is the relationship between the date delta and average rating?

4.    What is the relationship between total number of reviews and average?

4.    Which movie contains your word of interest at the highest frequency. Does that word have any relationship with average rating?